# ---------- Build dos assets React ----------
FROM node:22.16-alpine AS build

WORKDIR /app

# Copia package.json e package-lock.json para usar cache
COPY frontend/package.json frontend/package-lock.json ./

RUN npm install --no-audit

# Copia restante do código e roda build
COPY frontend/ ./
RUN npm run build

# ---------- Servidor estático NGINX ----------
FROM nginx:stable-alpine

# Remove as páginas padrão do nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia build da etapa anterior
COPY --from=build /app/dist /usr/share/nginx/html/

# Substitui configuração padrão do NGINX
COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]